{
 "title": "Logs & traces",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Traces: last 20 items",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "limit": 20 }
   ]
  },
  {
   "title": "Syslog logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{job=\"syslog\"}"
    }
   ]
  },
  {
   "title": "Apache logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"apache\"}"
    }
   ]
  },
  {
   "title": "Nginx logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "{job=\"nginx\"}"
    }
   ]
  }
 ]
}