name: Docker Compose test

on:
  push:
    branches:
      - compose
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Project
        uses: actions/checkout@v4
      - name: Set Up Docker Compose
        uses: docker/setup-compose-action@v1
      - name: Docker Compose start
        run: docker compose up -d
      - name: Docker Compose ps
        run: docker compose ps
      - name: Docker Compose down
        run: docker compose down
